apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: lecture19
data:
  NODE_ENV: "production"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "shop"
  DB_USERNAME: "postgres"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  PAYMENTS_GRPC_URL: "payments:5001"
  GRPC_URL: "0.0.0.0:5001"
  HTTP_PORT: "3001"
