services:
  postgres:
    image: postgres:16-alpine
    container_name: nestjs_shop_db_dev
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      target: migrations
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DB_HOST: postgres
    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy
    command: ["npm", "run", "migration:run:prod"]
    profiles:
      - tools

  seed:
    build:
      context: .
      target: migrations
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DB_HOST: postgres
    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy
    command: ["npm", "run", "seed:prod"]
    profiles:
      - tools

  api:
    build:
      context: .
      target: dev
    container_name: nestjs_shop_api_dev
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DB_HOST: postgres
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tsconfig.build.json:/app/tsconfig.build.json:ro
      - ./nest-cli.json:/app/nest-cli.json:ro
      - /app/node_modules
      - /app/dist
    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  dev:
    driver: bridge

volumes:
  pgdata_dev:
    driver: local
