apiVersion: v1
kind: Service
metadata:
  name: orders-api
  labels:
    app: orders-api
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    app: orders-api
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
spec:
  ports:
    - name: grpc
      port: 5001
      targetPort: 5001
    - name: http
      port: 3001
      targetPort: 3001
  selector:
    app: payments
